Repository aliencube/open-chat-playground, pull requests merged in 2025-10, with the labels that each got.

#472 Add hero image
  README.md
  assets/logo-inverted.png
  assets/logo.png
  images/ocp-hero.png
Labels: documentation, ossca, p1, phase-1, task, mentor

#474 Update docs to provide models page in the beginning
  docs/github-models.md
  docs/hugging-face.md
  docs/openai.md
Labels: documentation, enhancement, ossca, p1, phase-1, task, mentor

#486 Define endpoint
  README.md
  src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
  src/OpenChat.PlaygroundApp/Program.cs
Labels: enhancement, ossca, p1, phase-1, task, mentor

#487 Add `ChatService`
  src/OpenChat.PlaygroundApp/Services/ChatService.cs
  test/OpenChat.PlaygroundApp.Tests/Services/ChatServiceTests.cs
Labels: enhancement, ossca, p1, phase-1, task, mentor

#469 refactor: UI Component Refactoring - ChatMessageItem.razor
  src/OpenChat.PlaygroundApp/Components/Pages/Chat/ChatMessageItem.razor
  src/OpenChat.PlaygroundApp/Components/Pages/Chat/ChatMessageItem.razor.cs
  test/OpenChat.PlaygroundApp.Tests/Components/Pages/Chat/ChatMessageItemUITests.cs
Labels: ossca, p1, team-kim, phase-1, task

#489 Remove magic strings
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Constants/AppSettingConstants.cs
  src/OpenChat.PlaygroundApp/Constants/ArgumentOptionConstants.cs
  src/OpenChat.PlaygroundApp/Options/AmazonBedrockArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/AnthropicArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/AzureAIFoundryArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/FoundryLocalArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/GitHubModelsArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/GoogleVertexAIArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/HuggingFaceArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/LGArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/OllamaArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/OpenAIArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/UpstageArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/ArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/AmazonBedrockArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/AnthropicArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/AzureAIFoundryArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/FoundryLocalArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/GitHubModelsArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/GoogleVertexAIArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/HuggingFaceArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/LGArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/OllamaArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/OpenAIArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/UpstageArgumentOptionsTests.cs
Labels: enhancement, ossca, p1, team-park, phase-1, task

#492 Update bicep files to serve Ollama server
  azure.yaml
  docs/github-models.md
  docs/hugging-face.md
  docs/openai.md
  infra/main.bicep
  infra/main.parameters.json
  infra/resources.bicep
  src/OpenChat.PlaygroundApp/Connectors/GitHubModelsConnector.cs
  src/OpenChat.PlaygroundApp/Connectors/HuggingFaceConnector.cs
  src/OpenChat.PlaygroundApp/Connectors/OpenAIConnector.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelConnectorTests.cs
  test/OpenChat.PlaygroundApp.Tests/Connectors/GitHubModelsConnectorTests.cs
  test/OpenChat.PlaygroundApp.Tests/Connectors/HuggingFaceConnectorTests.cs
  test/OpenChat.PlaygroundApp.Tests/Connectors/OpenAIConnectorTests.cs
Labels: documentation, enhancement, ossca, p1, phase-1, task, local, mentor
