Repository aliencube/open-chat-playground, pull requests merged in 2025-08, with the labels that each got.

#290 Add comprehensive unit tests for environment variables integration in…
  test/OpenChat.PlaygroundApp.Tests/Options/GitHubModelsArgumentOptionsTests.cs
Labels: task

#321 Refactor `DisplayHelp()`
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
Labels: ossca, p0, task, mentor, phase-0

#356 feat: add Hugging Face settings to appsettings.json
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: ossca, p1, team-park, phase-1, task, local

#364 feat: add Upstage Solar API configuration to appsettings.json
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: ossca, p1, lead, phase-1, task, vendor

#365 feat: add Hugging Face settings configuration
  src/OpenChat.PlaygroundApp/Configurations/HuggingFaceSettings.cs
Labels: ossca, p1, team-park, phase-1, task, local

#368 Update README
  README.md
Labels: documentation, ossca, p1, phase-1, task, mentor

#369 feat/266 model class implementation ollama
  src/OpenChat.PlaygroundApp/Configurations/OllamaSettings.cs
Labels: ossca, p1, team-park, phase-1, task, local

#366 feat: add Hugging Face argument options class
  src/OpenChat.PlaygroundApp/Options/HuggingFaceArgumentOptions.cs
Labels: ossca, p1, team-park, phase-1, task, local

#372 feat: add OpenAI settings to appsettings.json
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: ossca, p1, team-park, phase-1, task, maas

#374 Add Azure.AI.OpenAI NuGet package for Azure AI Foundry support
  licenses/azure.ai.openai.md
  src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
Labels: ossca, p1, team-kim, phase-1, task, maas

#383 Delete azure.ai.openai.md
  licenses/azure.ai.openai.md
Labels: ossca, p1, phase-1, task, mentor

#375 feat: Add NuGet package: Hugging Face #337
  src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
Labels: ossca, p1, team-jeon, phase-1, task, local

#386 feat: Model Class Implementation - OpenAI GPT
  src/OpenChat.PlaygroundApp/Configurations/OpenAISettings.cs
Labels: ossca, p1, team-kim, phase-1, task, vendor

#378 feat: add Google Vertex AI settings params to appsettings.json
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: ossca, p1, phase-1, task, maas, mentor

#381 Feature/add foundry local nuget package
  src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
Labels: ossca, p1, lead, phase-1, task, local

#390 feat: Add OllamaArgumentOptions for command-line argument modelling
  src/OpenChat.PlaygroundApp/Options/OllamaArgumentOptions.cs
Labels: ossca, p1, team-park, phase-1, task, local

#388 feat: add API connection details of Foundry Local to appsettings.json
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: ossca, p1, phase-1, task, local, mentor

#392 feat: Add new AzureAIFoundrySettings
  src/OpenChat.PlaygroundApp/Configurations/AzureAIFoundrySettings.cs
Labels: ossca, p1, team-park, phase-1, task, maas

#393 feature/343-Add-NuGet-package-Anthropic-Claude
  src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
Labels: ossca, p1, team-kim, phase-1, task, vendor

#391 feat: add Amazon Bedrock configuration to appsettings.json
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: ossca, p1, team-kim, phase-1, task, maas

#379 feat: add Hugging Face argument options parsing logic
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/HuggingFaceArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/ArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/HuggingFaceArgumentOptionsTests.cs
Labels: ossca, p1, team-park, phase-1, task, local

#399 feat: add Command-Line Argument Options Modeling for Azure AI Foundry
  src/OpenChat.PlaygroundApp/Options/AzureAIFoundryArgumentOptions.cs
Labels: ossca, p1, team-park, phase-1, task, maas

#394 feat: add GoogleVertexAIArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/GoogleVertexAIArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/ArgumentOptionsTests.cs
Labels: ossca, p1, phase-1, task, maas, mentor

#403 Model Class Implementation: Foundry Local #211
  src/OpenChat.PlaygroundApp/Configurations/FoundryLocalSettings.cs
Labels: ossca, p1, phase-1, task, local, mentor

#398 LG exaone app settings
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: ossca, p1, team-jeon, phase-1, task, vendor
