Repository aliencube/open-chat-playground, pull requests merged in 2025-09, with the labels that each got.

#402 Environment Variables Testing: Hugging Face
  test/OpenChat.PlaygroundApp.Tests/Options/HuggingFaceArgumentOptionsTests.cs
Labels: ossca, p1, team-park, phase-1, task, local

#408 feature/Model-Class-Implementation-Anthropic-Claude
  src/OpenChat.PlaygroundApp/Configurations/AnthropicSettings.cs
Labels: ossca, p1, team-kim, phase-1, task, vendor

#411 feat: add Amazon Bedrock settings configuration class
  src/OpenChat.PlaygroundApp/Configurations/AmazonBedrockSettings.cs
Labels: ossca, p1, team-kim, phase-1, task, maas

#417 Add azd template
  .gitignore
  azure.yaml
  infra/abbreviations.json
  infra/main.bicep
  infra/main.parameters.json
  infra/modules/fetch-container-image.bicep
  infra/resources.bicep
Labels: enhancement, ossca, p1, phase-1, task, mentor

#420 Command-Line Argument Modelling: LG Exaone #344
  src/OpenChat.PlaygroundApp/Options/LGArgumentOptions.cs
Labels: ossca, p1, team-jeon, phase-1, task, vendor

#421 feat: Command-Line Argument Parsing: OpenAI GPT
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/OpenAIArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Options/OpenAIArgumentOptionsTests.cs
Labels: ossca, p1, team-kim, phase-1, task, vendor

#426 enhance: add inheritance tests
  test/OpenChat.PlaygroundApp.Tests/Abstractions/ArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelConnectorTests.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelSettings.cs
Labels: enhancement, ossca, p0, phase-1, mentor

#410 feat: add parsing Command-Line Argument for Google Vertex AI
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/GoogleVertexAIArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Options/GoogleVertexAIArgumentOptionsTests.cs
Labels: ossca, p1, team-park, phase-1, task, maas

#400 feat: add parsing Command-Line Argument for Azure AI Foundry
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/AzureAIFoundryArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Options/AzureAIFoundryArgumentOptionsTests.cs
Labels: ossca, p1, team-park, phase-1, task, maas

#432 feat: add DocerModelRunnerSettings
  src/OpenChat.PlaygroundApp/Configurations/DockerModelRunnerSettings.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelSettings.cs
Labels: ossca, p1, phase-1, task, local, mentor

#434 Add `EnsureLanguageModelSettingsValid()` for settings verification
  src/OpenChat.PlaygroundApp/Abstractions/LanguageModelConnector.cs
  src/OpenChat.PlaygroundApp/Connectors/GitHubModelsConnector.cs
  src/OpenChat.PlaygroundApp/Connectors/OpenAIConnector.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelConnectorTests.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelSettingsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Connectors/GitHubModelsConnectorTests.cs
  test/OpenChat.PlaygroundApp.Tests/Connectors/OpenAIConnectorTests.cs
Labels: enhancement, ossca, p0, phase-1, task, mentor

#437 Update appsettings.json
  src/OpenChat.PlaygroundApp/appsettings.json
Labels: p1, phase-1, task, vendor, mentor

#438 feat: Command-Line Argument Parsing: Anthropic Claude #259
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/AnthropicArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Abstractions/ArgumentOptionsTests.cs
  test/OpenChat.PlaygroundApp.Tests/Options/AnthropicArgumentOptionsTests.cs
Labels: ossca, p1, team-park, phase-1, task, vendor

#442 Feature/231 upstage command line argument parsing
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/UpstageArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Options/UpstageArgumentOptionsTests.cs
Labels: ossca, p1, lead, phase-1, task, vendor

#449 LG AI EXAONE command-line argument parsing
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/LGArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Options/LGArgumentOptionsTests.cs
Labels: ossca, p1, team-jeon, phase-1, task, vendor

#452 refactor: UI Component Refactoring - ChatHeader.razor
  src/OpenChat.PlaygroundApp/Components/Pages/Chat/ChatHeader.razor
  src/OpenChat.PlaygroundApp/Components/Pages/Chat/ChatHeader.razor.cs
  test/OpenChat.PlaygroundApp.Tests/Components/Pages/Chat/ChatHeaderUITests.cs
Labels: ossca, p1, team-kim, phase-1, task

#460 feat: add parsing Command-Line Argument for Amazon Bedrock
  src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
  src/OpenChat.PlaygroundApp/Options/AmazonBedrockArgumentOptions.cs
  test/OpenChat.PlaygroundApp.Tests/Options/AmazonBedrockArgumentOptionsTests.cs
Labels: ossca, p1, team-kim, phase-1, task, maas

#459 refactor: UI Component Refactoring - ChatInput.razor
  src/OpenChat.PlaygroundApp/Components/Pages/Chat/ChatInput.razor
  src/OpenChat.PlaygroundApp/Components/Pages/Chat/ChatInput.razor.cs
  test/OpenChat.PlaygroundApp.Tests/Components/Pages/Chat/ChatInputUITests.cs
Labels: ossca, p1, team-kim, phase-1, task

#429 feat: Connector Implementation & Inheritance: OpenAI GPT #220
  .github/workflows/azure-dev.yml
  README.md
  docs/README.md
  docs/openai.md
  infra/main.bicep
  infra/main.parameters.json
  infra/resources.bicep
  test/OpenChat.PlaygroundApp.Tests/Connectors/OpenAIConnectorTests.cs
Labels: ossca, p1, team-jeon, phase-1, task, vendor

#466 Environment Variables Testing: Anthropic Claude
  test/OpenChat.PlaygroundApp.Tests/Options/AnthropicArgumentOptionsTests.cs
Labels: ossca, p1, team-park, phase-1, task, vendor
